version: '2'

services:

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1
      
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    expose:
      - 9200
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:6.0.1

    command: "logstash -f /usr/share/logstash/pipeline/logstash.conf"
      
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      
    ports:
      - "5000:5000"
      - "9600:9600"
    expose:
      - 5000
      - 9600
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.0.1
      
    volumes:
      - ./kibana/config:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    expose:
      - 5601
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: unless-stopped

networks:

  elk:
    driver: bridge